version: 2.1

jobs:
  test:  # required for runs that don't use workflows
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - run:
          name: Run unit testing
          command: python test_calculate_cli.py
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t moving-average .

      - run: mkdir -p docker-cache
      - run: docker save -o docker-cache/built-image.tar moving-average

      - save_cache:
          key: docker-key
          paths:
            - docker-cache

  publish:
    machine: true
    steps:
      - restore_cache:
          keys:
            - docker-key
      - run: docker load < docker-cache/built-image.tar
      - run: docker tag moving-average $DOCKER_USER/moving-average
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $DOCKER_USER/moving-average


workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - build:
          requires:
            - test
          context: moving-average
      - publish:
          requires:
            - build
          context: moving-average