version: 2.1

jobs:
  test:  # required for runs that don't use workflows
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - run:
          name: Run unit testing
          command: python test_calculate_cli.py
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test